name: tech_task
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  fluttertoast: ^8.0.3
  get_it: ^6.1.1
  google_fonts: ^2.0.0
  intl: ^0.17.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.4

flutter:

  uses-material-design: true
  # assets:
  #  - assets/
